-- MySQL Script generated by MySQL Workbench
-- Wed Dec  8 20:51:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_crm` DEFAULT CHARACTER SET utf8 ;
USE `bd_crm` ;

-- -----------------------------------------------------
-- Table `bd_crm`.`tb_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_empresa` (
  `idtb_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(45) NOT NULL,
  `ruc_empresa` INT(11) NOT NULL,
  `correo_empresa` VARCHAR(45) NOT NULL,
  `telefono_empresa` INT(9) NOT NULL,
  PRIMARY KEY (`idtb_empresa`),
  UNIQUE INDEX `nombre_empresa_UNIQUE` (`nombre_empresa` ASC),
  UNIQUE INDEX `ruc_empresa_UNIQUE` (`ruc_empresa` ASC),
  UNIQUE INDEX `telefono_empresa_UNIQUE` (`telefono_empresa` ASC),
  UNIQUE INDEX `correo_empresa_UNIQUE` (`correo_empresa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_empleado` (
  `idtb_empleado` INT NOT NULL AUTO_INCREMENT,
  `idtb_empresa` INT NOT NULL,
  `estado_empleado` TINYINT NOT NULL,
  `usuario_empleado` VARCHAR(10) NOT NULL,
  `contraseña` VARCHAR(8) NOT NULL,
  `nombre_empleado` VARCHAR(45) NOT NULL,
  `correo_empleado` VARCHAR(55) NOT NULL,
  `telefono_empleado` INT(9) NOT NULL,
  PRIMARY KEY (`idtb_empleado`),
  UNIQUE INDEX `usuario_empleado_UNIQUE` (`usuario_empleado` ASC),
  UNIQUE INDEX `telefono_empleado_UNIQUE` (`telefono_empleado` ASC),
  UNIQUE INDEX `correo_empleado_UNIQUE` (`correo_empleado` ASC),
  INDEX `fk_tb_empresa_idx` (`idtb_empresa` ASC),
  CONSTRAINT `fk_tb_empresa`
    FOREIGN KEY (`idtb_empresa`)
    REFERENCES `bd_crm`.`tb_empresa` (`idtb_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_rol` (
  `idtb_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL,
  `estado_rol` TINYINT NOT NULL,
  PRIMARY KEY (`idtb_rol`),
  UNIQUE INDEX `nombre_rol_UNIQUE` (`nombre_rol` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_rolempleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_rolempleado` (
  `idtb_rol` INT NOT NULL,
  `idtb_empleado` INT NOT NULL,
  INDEX `fk_tb_empleado_idx` (`idtb_empleado` ASC),
  PRIMARY KEY (`idtb_rol`, `idtb_empleado`),
  CONSTRAINT `fk_tb_empleado`
    FOREIGN KEY (`idtb_empleado`)
    REFERENCES `bd_crm`.`tb_empleado` (`idtb_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_rol`
    FOREIGN KEY (`idtb_rol`)
    REFERENCES `bd_crm`.`tb_rol` (`idtb_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_cliente` (
  `idtb_cliente` INT NOT NULL AUTO_INCREMENT,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATETIME(6) NOT NULL,
  `nombre_cliente` VARCHAR(55) NOT NULL,
  `correo cliente` VARCHAR(55) NOT NULL,
  `telefono_cliente` INT(9) NOT NULL,
  `direccion_cliente` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idtb_cliente`),
  UNIQUE INDEX `correo cliente_UNIQUE` (`correo cliente` ASC),
  UNIQUE INDEX `telefono_cliente_UNIQUE` (`telefono_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_canales` (
  `idtb_canales` INT NOT NULL,
  `tipo_canal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_canales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_producto` (
  `idtb_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(55) NOT NULL,
  `precio_producto` DECIMAL(2) NOT NULL,
  `stock_producto` INT(2) NOT NULL,
  PRIMARY KEY (`idtb_producto`),
  UNIQUE INDEX `nombre_producto_UNIQUE` (`nombre_producto` ASC),
  UNIQUE INDEX `precio_producto_UNIQUE` (`precio_producto` ASC),
  UNIQUE INDEX `stock_producto_UNIQUE` (`stock_producto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_pedidos` (
  `idtb_pedidos` INT NOT NULL AUTO_INCREMENT,
  `idtb_canales` INT NOT NULL,
  `idtb_cliente` INT NOT NULL,
  `idtb_empleado` INT NOT NULL,
  `fecha_pedido` DATETIME(6) NOT NULL,
  `fecha_entrega` DATETIME(6) NOT NULL,
  `fecha_envio` DATETIME(6) NOT NULL,
  `forma_envio` VARCHAR(45) NOT NULL,
  `direccion_envio` VARCHAR(55) NULL,
  `estado_pedido` TINYINT NOT NULL,
  `metodo_pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_pedidos`),
  INDEX `fk_tb_canales_idx` (`idtb_canales` ASC),
  INDEX `fk_tb_cliente_idx` (`idtb_cliente` ASC),
  INDEX `fk_tb_empleado_idx` (`idtb_empleado` ASC),
  CONSTRAINT `fk_tb_canales`
    FOREIGN KEY (`idtb_canales`)
    REFERENCES `bd_crm`.`tb_canales` (`idtb_canales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_clientes`
    FOREIGN KEY (`idtb_cliente`)
    REFERENCES `bd_crm`.`tb_cliente` (`idtb_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_empleados`
    FOREIGN KEY (`idtb_empleado`)
    REFERENCES `bd_crm`.`tb_empleado` (`idtb_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_crm`.`tb_detallespedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_crm`.`tb_detallespedido` (
  `idtb_pedidos` INT NOT NULL,
  `idtb_producto` INT NOT NULL,
  `cant_producto` INT(2) NOT NULL,
  `precio_unidad` DECIMAL(2) NOT NULL,
  `descuento` DECIMAL(2) NULL,
  PRIMARY KEY (`idtb_pedidos`, `idtb_producto`),
  INDEX `fk_tb_producto_idx` (`idtb_producto` ASC),
  INDEX `fk_tb_pedidos_idx` (`idtb_pedidos` ASC),
  CONSTRAINT `fk_tb_productos`
    FOREIGN KEY (`idtb_producto`)
    REFERENCES `bd_crm`.`tb_producto` (`idtb_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedidos`
    FOREIGN KEY (`idtb_pedidos`)
    REFERENCES `bd_crm`.`tb_pedidos` (`idtb_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
