/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.clogin;
import Modelo.mempleado;
import javax.swing.JOptionPane;

/**
 *
 * @author SISTEMAS
 */
public class vlogin extends javax.swing.JFrame {

    /**
     * Creates new form vlogin
     */
    public vlogin() {
        initComponents();
    }
    
    mempleado me = new mempleado();
    clogin login = new clogin();
    
    public void validar(){
        String usuario = txt_usuariologin.getText();
        String clave = String.valueOf(txt_contraseñalogin.getPassword());
        
        if (!"".equals(usuario) || !"".equals(clave)){
            me = login.log(usuario, clave);
            if(me.getUsuario_empleado() != null && me.getContraseña() != null){
                vmenu menu = new vmenu();
                menu.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrecta");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingresa usuario o contraseña");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_login = new javax.swing.JPanel();
        lbl_salesforce = new javax.swing.JLabel();
        txt_contraseñalogin = new javax.swing.JPasswordField();
        txt_usuariologin = new javax.swing.JTextField();
        btn_acceder = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_login = new javax.swing.JLabel();
        lbl_iniciarsesion = new javax.swing.JLabel();
        lbl_usuariologin = new javax.swing.JLabel();
        lbl_contraseñalogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        panel_login.setBackground(new java.awt.Color(255, 255, 255));

        lbl_salesforce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/login.jpg"))); // NOI18N
        lbl_salesforce.setToolTipText("");

        txt_contraseñalogin.setForeground(new java.awt.Color(204, 204, 204));
        txt_contraseñalogin.setToolTipText("Contraseña");
        txt_contraseñalogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_contraseñalogin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        txt_contraseñalogin.setDisabledTextColor(new java.awt.Color(187, 134, 252));
        txt_contraseñalogin.setName("Contraseña"); // NOI18N

        txt_usuariologin.setForeground(new java.awt.Color(204, 204, 204));
        txt_usuariologin.setToolTipText("");
        txt_usuariologin.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(187, 134, 252)));
        txt_usuariologin.setCaretColor(new java.awt.Color(187, 134, 252));
        txt_usuariologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuariologinActionPerformed(evt);
            }
        });

        btn_acceder.setBackground(new java.awt.Color(187, 134, 252));
        btn_acceder.setText("Acceder");
        btn_acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_accederMouseClicked(evt);
            }
        });
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });

        lbl_login.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(187, 134, 252));
        lbl_login.setText("LOGIN");

        lbl_iniciarsesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_iniciarsesion.setText("Iniciar Sesión");

        lbl_usuariologin.setText("USUARIO");

        lbl_contraseñalogin.setText("CONTRASEÑA");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(519, 519, 519)
                        .addComponent(jSeparator1))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addComponent(lbl_salesforce, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_login)
                                    .addComponent(lbl_iniciarsesion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_acceder, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_usuariologin)
                                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_contraseñalogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                        .addComponent(txt_usuariologin))
                                    .addComponent(lbl_contraseñalogin))))))
                .addContainerGap())
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_iniciarsesion)
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lbl_usuariologin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_usuariologin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbl_contraseñalogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contraseñalogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_acceder, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_salesforce, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        txt_contraseñalogin.getAccessibleContext().setAccessibleName("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuariologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuariologinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuariologinActionPerformed

    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_accederActionPerformed

    private void btn_accederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accederMouseClicked
        validar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_accederMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acceder;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_contraseñalogin;
    private javax.swing.JLabel lbl_iniciarsesion;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_salesforce;
    private javax.swing.JLabel lbl_usuariologin;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPasswordField txt_contraseñalogin;
    private javax.swing.JTextField txt_usuariologin;
    // End of variables declaration//GEN-END:variables
}
