/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ccanales;
import Controlador.cclientes;
import Controlador.cpedidos;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SISTEMAS
 */
public class vmenu extends javax.swing.JFrame {

    /**
     * Creates new form vmenu
     */
    public vmenu() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JLabel();
        btnClientes = new javax.swing.JLabel();
        btnCanales = new javax.swing.JLabel();
        btnVentas = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Panel_inicio = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbltotalganancias = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbltotalclientes = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbltotalventas = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbltotalpedidos = new javax.swing.JLabel();
        Panel_cliente = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        Panel_canales = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablalistadoChat = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablalistadoWhatsapp = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablalistadoFacebook = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Panel_ventas = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablalistadoVentas = new javax.swing.JTable();
        Panel_ajustes = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(187, 134, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cmtec.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 60));

        jLabel1.setBackground(new java.awt.Color(243, 243, 243));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cerrar Sesión");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 130, 40));

        btnInicio.setBackground(new java.awt.Color(203, 108, 230));
        btnInicio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInicio.setText("Inicio");
        btnInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        btnInicio.setOpaque(true);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, 40));

        btnClientes.setBackground(new java.awt.Color(243, 243, 243));
        btnClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(51, 51, 51));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClientes.setText("Clientes");
        btnClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        btnClientes.setOpaque(true);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        jPanel2.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, 40));

        btnCanales.setBackground(new java.awt.Color(243, 243, 243));
        btnCanales.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCanales.setForeground(new java.awt.Color(51, 51, 51));
        btnCanales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCanales.setText("Canales");
        btnCanales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        btnCanales.setOpaque(true);
        btnCanales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCanalesMouseClicked(evt);
            }
        });
        jPanel2.add(btnCanales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 40));

        btnVentas.setBackground(new java.awt.Color(243, 243, 243));
        btnVentas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(51, 51, 51));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVentas.setText("Ventas");
        btnVentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        btnVentas.setOpaque(true);
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
        });
        jPanel2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, 40));

        btnAjustes.setBackground(new java.awt.Color(243, 243, 243));
        btnAjustes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAjustes.setForeground(new java.awt.Color(51, 51, 51));
        btnAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjustes.setText("Ajustes");
        btnAjustes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        btnAjustes.setOpaque(true);
        btnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjustesMouseClicked(evt);
            }
        });
        jPanel2.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, 40));

        jLabel3.setBackground(new java.awt.Color(243, 243, 243));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Salir");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 130, 40));

        jPanel3.setBackground(new java.awt.Color(140, 82, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CM TÉC");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total de ganancias");
        jLabel9.setOpaque(true);

        lbltotalganancias.setBackground(new java.awt.Color(204, 204, 255));
        lbltotalganancias.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbltotalganancias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotalganancias.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltotalganancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalganancias, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total de Clientes");
        jLabel11.setOpaque(true);

        lbltotalclientes.setBackground(new java.awt.Color(204, 204, 255));
        lbltotalclientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbltotalclientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotalclientes.setOpaque(true);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltotalclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalclientes, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total de ventas");
        jLabel13.setOpaque(true);

        lbltotalventas.setBackground(new java.awt.Color(204, 204, 255));
        lbltotalventas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbltotalventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotalventas.setOpaque(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltotalventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalventas, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total de Pedidos");
        jLabel15.setOpaque(true);

        lbltotalpedidos.setBackground(new java.awt.Color(204, 204, 255));
        lbltotalpedidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbltotalpedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotalpedidos.setOpaque(true);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltotalpedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalpedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        javax.swing.GroupLayout Panel_inicioLayout = new javax.swing.GroupLayout(Panel_inicio);
        Panel_inicio.setLayout(Panel_inicioLayout);
        Panel_inicioLayout.setHorizontalGroup(
            Panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_inicioLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_inicioLayout.setVerticalGroup(
            Panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_inicioLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 850, Short.MAX_VALUE))
        );

        jPanel4.add(Panel_inicio, "card2");

        Panel_cliente.setBackground(new java.awt.Color(255, 255, 255));
        Panel_cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 330, 10));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Cliente");
        jLabel17.setOpaque(true);
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 330, 30));

        Panel_cliente.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 60));

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Telefono", "Direccion", "Tipo Cliente", "Fecha creacion"
            }
        ));
        tablalistado.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablalistado);
        if (tablalistado.getColumnModel().getColumnCount() > 0) {
            tablalistado.getColumnModel().getColumn(1).setHeaderValue("Correo");
            tablalistado.getColumnModel().getColumn(2).setHeaderValue("Telefono");
            tablalistado.getColumnModel().getColumn(3).setHeaderValue("Direccion");
            tablalistado.getColumnModel().getColumn(4).setHeaderValue("Tipo Cliente");
            tablalistado.getColumnModel().getColumn(5).setHeaderValue("Fecha creacion");
        }

        Panel_cliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 650, 340));

        jLabel18.setBackground(new java.awt.Color(203, 108, 230));
        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Nuevo cliente");
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel18.setOpaque(true);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        Panel_cliente.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 40));

        jPanel4.add(Panel_cliente, "card3");

        Panel_canales.setBackground(new java.awt.Color(255, 255, 255));
        Panel_canales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 10));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Whatsapp");
        jLabel32.setOpaque(true);
        jPanel17.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        Panel_canales.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 40));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 10));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Chat");
        jLabel19.setOpaque(true);
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        Panel_canales.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        tablalistadoChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Chat"
            }
        ));
        tablalistadoChat.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tablalistadoChat);

        Panel_canales.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 710, 80));

        tablalistadoWhatsapp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Whatsapp"
            }
        ));
        tablalistadoWhatsapp.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tablalistadoWhatsapp);

        Panel_canales.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 710, 90));

        tablalistadoFacebook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Facebook"
            }
        ));
        tablalistadoFacebook.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(tablalistadoFacebook);

        Panel_canales.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 710, 90));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 330, 10));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Canales");
        jLabel26.setOpaque(true);
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 330, 30));

        jLabel20.setBackground(new java.awt.Color(203, 108, 230));
        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Nuevo Pedido");
        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 130, 40));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 10));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Chat");
        jLabel28.setOpaque(true);
        jPanel16.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 190, 60));

        Panel_canales.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 60));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 10));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Facebook");
        jLabel30.setOpaque(true);
        jPanel18.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        Panel_canales.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 190, 60));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Telefono");
        jLabel27.setOpaque(true);
        Panel_canales.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        jPanel4.add(Panel_canales, "card4");

        Panel_ventas.setBackground(new java.awt.Color(255, 255, 255));
        Panel_ventas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(203, 108, 230));
        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Nuevo venta");
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        Panel_ventas.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 40));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 330, 10));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Ventas");
        jLabel21.setOpaque(true);
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 330, 30));

        Panel_ventas.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 60));

        tablalistadoVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Canal", "Cliente", "Empleado", "Fecha Pedido", "Fecha Entrega", "Fecha Envio", "Estado", "Metodo de Pago", "Total"
            }
        ));
        tablalistadoVentas.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(tablalistadoVentas);

        Panel_ventas.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 650, 370));

        jPanel4.add(Panel_ventas, "card5");

        Panel_ajustes.setBackground(new java.awt.Color(255, 255, 255));
        Panel_ajustes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 330, 10));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Ajustes");
        jLabel23.setOpaque(true);
        jPanel13.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 330, 30));

        Panel_ajustes.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 60));

        jLabel24.setBackground(new java.awt.Color(203, 108, 230));
        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Nuevo Empleado");
        jLabel24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        Panel_ajustes.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 130, 40));

        jLabel25.setBackground(new java.awt.Color(203, 108, 230));
        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Empresa");
        jLabel25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        Panel_ajustes.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 40));

        jLabel31.setBackground(new java.awt.Color(203, 108, 230));
        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Listar Empleados");
        jLabel31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(187, 134, 252), new java.awt.Color(187, 134, 252), null, null));
        jLabel31.setOpaque(true);
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        Panel_ajustes.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 40));

        jPanel4.add(Panel_ajustes, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
                // TODO add your handling code here:
        Panel_inicio.setVisible(true);
        Panel_cliente.setVisible(false);
        Panel_canales.setVisible(false);
        Panel_ventas.setVisible(false);
        Panel_ajustes.setVisible(false);
        
        btnInicio.setBackground(new java.awt.Color(203,108,230));
        btnInicio.setForeground(new java.awt.Color(255,255,255));
        
        btnClientes.setBackground(new java.awt.Color(243,243,243));
        btnClientes.setForeground(new java.awt.Color(11,10,9));
        
        btnCanales.setBackground(new java.awt.Color(243,243,243));
        btnCanales.setForeground(new java.awt.Color(11,10,9));
        
        btnVentas.setBackground(new java.awt.Color(243,243,243));
        btnVentas.setForeground(new java.awt.Color(11,10,9));
        
        btnAjustes.setBackground(new java.awt.Color(243,243,243));
        btnAjustes.setForeground(new java.awt.Color(11,10,9));
        
        try {
            
            cclientes func = new cclientes();
            lbltotalclientes.setText(Integer.toString(func.mostrarTotal()));
            
            cpedidos funp = new cpedidos();
            lbltotalventas.setText(Integer.toString(funp.mostrarTotalVentas()));
            lbltotalpedidos.setText(Integer.toString(funp.mostrarTotalPedidos()));
            lbltotalganancias.setText(Integer.toString(funp.mostrarTotalGanancias()));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        
        
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        
        Panel_inicio.setVisible(false);
        Panel_cliente.setVisible(true);
        Panel_canales.setVisible(false);
        Panel_ventas.setVisible(false);
        Panel_ajustes.setVisible(false);
        
        
        btnClientes.setBackground(new java.awt.Color(203,108,230));
        btnClientes.setForeground(new java.awt.Color(255,255,255));
        
        btnInicio.setBackground(new java.awt.Color(243,243,243));
        btnInicio.setForeground(new java.awt.Color(11,10,9));
        
        btnCanales.setBackground(new java.awt.Color(243,243,243));
        btnCanales.setForeground(new java.awt.Color(11,10,9));
        
        btnVentas.setBackground(new java.awt.Color(243,243,243));
        btnVentas.setForeground(new java.awt.Color(11,10,9));
        
        btnAjustes.setBackground(new java.awt.Color(243,243,243));
        btnAjustes.setForeground(new java.awt.Color(11,10,9));
        
        DefaultTableModel modelo;
        cclientes func = new cclientes();
        modelo = func.mostrar();
        
        tablalistado.setModel(modelo);
        
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnCanalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanalesMouseClicked
        // TODO add your handling code here:

        Panel_inicio.setVisible(false);
        Panel_cliente.setVisible(false);
        Panel_canales.setVisible(true);
        Panel_ventas.setVisible(false);
        Panel_ajustes.setVisible(false);
        
        btnCanales.setBackground(new java.awt.Color(203,108,230));
        btnCanales.setForeground(new java.awt.Color(255,255,255));
        
        
        btnClientes.setBackground(new java.awt.Color(243,243,243));
        btnClientes.setForeground(new java.awt.Color(11,10,9));
        
        btnInicio.setBackground(new java.awt.Color(243,243,243));
        btnInicio.setForeground(new java.awt.Color(11,10,9));
        
        btnVentas.setBackground(new java.awt.Color(243,243,243));
        btnVentas.setForeground(new java.awt.Color(11,10,9));
        
        btnAjustes.setBackground(new java.awt.Color(243,243,243));
        btnAjustes.setForeground(new java.awt.Color(11,10,9));
        
        DefaultTableModel modeloChat;
        DefaultTableModel modeloTelefono;
        DefaultTableModel modeloWhatsapp;
        DefaultTableModel modeloFacebook;
        
        ccanales func = new ccanales();
        
        modeloChat = func.mostrar(1);
        tablalistadoChat.setModel(modeloChat);
        
        modeloWhatsapp = func.mostrar(2);
        tablalistadoWhatsapp.setModel(modeloWhatsapp);
        
        modeloFacebook = func.mostrar(3);
        tablalistadoFacebook.setModel(modeloFacebook);
        
        
    }//GEN-LAST:event_btnCanalesMouseClicked

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
        // TODO add your handling code here:
        
        Panel_inicio.setVisible(false);
        Panel_cliente.setVisible(false);
        Panel_canales.setVisible(false);
        Panel_ventas.setVisible(true);
        Panel_ajustes.setVisible(false);
        
        btnVentas.setBackground(new java.awt.Color(203,108,230));
        btnVentas.setForeground(new java.awt.Color(255,255,255));
        
        btnCanales.setBackground(new java.awt.Color(243,243,243));
        btnCanales.setForeground(new java.awt.Color(11,10,9));
        
        btnClientes.setBackground(new java.awt.Color(243,243,243));
        btnClientes.setForeground(new java.awt.Color(11,10,9));
        
        btnInicio.setBackground(new java.awt.Color(243,243,243));
        btnInicio.setForeground(new java.awt.Color(11,10,9));

        btnAjustes.setBackground(new java.awt.Color(243,243,243));
        btnAjustes.setForeground(new java.awt.Color(11,10,9));
        
        DefaultTableModel modelo;
        cpedidos func = new cpedidos();
        
        modelo = func.mostrar();
        tablalistadoVentas.setModel(modelo);
        
    }//GEN-LAST:event_btnVentasMouseClicked

    private void btnAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseClicked
        // TODO add your handling code here:
        
        Panel_inicio.setVisible(false);
        Panel_cliente.setVisible(false);
        Panel_canales.setVisible(false);
        Panel_ventas.setVisible(false);
        Panel_ajustes.setVisible(true);
        
        btnAjustes.setBackground(new java.awt.Color(203,108,230));
        btnAjustes.setForeground(new java.awt.Color(255,255,255));
        
        btnVentas.setBackground(new java.awt.Color(243,243,243));
        btnVentas.setForeground(new java.awt.Color(11,10,9));
        
        btnCanales.setBackground(new java.awt.Color(243,243,243));
        btnCanales.setForeground(new java.awt.Color(11,10,9));
        
        btnClientes.setBackground(new java.awt.Color(243,243,243));
        btnClientes.setForeground(new java.awt.Color(11,10,9));
        
        btnInicio.setBackground(new java.awt.Color(243,243,243));
        btnInicio.setForeground(new java.awt.Color(11,10,9));

    }//GEN-LAST:event_btnAjustesMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        vlogin ir = new vlogin();
        ir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        vempresa ir = new vempresa();
        ir.setVisible(true);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        vClientes ir = new vClientes();
        ir.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        vpedidos ir = new vpedidos();
        ir.setVisible(true);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        vlistarpedidos ir = new vlistarpedidos();
        ir.setVisible(true);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        vregistro ir = new vregistro();
        ir.setVisible(true);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        vempleados ir = new vempleados();
        ir.setVisible(true);
    }//GEN-LAST:event_jLabel31MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_ajustes;
    private javax.swing.JPanel Panel_canales;
    private javax.swing.JPanel Panel_cliente;
    private javax.swing.JPanel Panel_inicio;
    private javax.swing.JPanel Panel_ventas;
    private javax.swing.JLabel btnAjustes;
    private javax.swing.JLabel btnCanales;
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JLabel btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbltotalclientes;
    private javax.swing.JLabel lbltotalganancias;
    private javax.swing.JLabel lbltotalpedidos;
    private javax.swing.JLabel lbltotalventas;
    private javax.swing.JTable tablalistado;
    private javax.swing.JTable tablalistadoChat;
    private javax.swing.JTable tablalistadoFacebook;
    private javax.swing.JTable tablalistadoVentas;
    private javax.swing.JTable tablalistadoWhatsapp;
    // End of variables declaration//GEN-END:variables
}
