/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.cpedidos;
import Modelo.mdetallespedido;
import Modelo.mpedidos;
import Modelo.mproducto;
import java.util.Calendar;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SISTEMAS
 */
public class vpedidos extends javax.swing.JFrame {

    /**
     * Creates new form vpedidos
     */
    
    cpedidos cp = new cpedidos();
    mpedidos mp = new mpedidos();
    mproducto pro = new mproducto();
    DefaultTableModel modelo = new DefaultTableModel();
    int item;
    double totalpagar = 0.00;
    mdetallespedido md = new mdetallespedido();
    
    public vpedidos() {
        initComponents();
        cp.consultarEmpleado(cbo_empleado);
        cp.consultarCliente(cbo_cliente);
        cp.consultarCanal(cbo_canal);
        cp.consultarProductos(cbo_productos);
        txt_totalpagar.setEnabled(false);
        txt_idproc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_nempresa1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_nombre1 = new javax.swing.JLabel();
        lb_ruc1 = new javax.swing.JLabel();
        lb_correo1 = new javax.swing.JLabel();
        lb_telefono1 = new javax.swing.JLabel();
        btn_crear1 = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        cbo_empleado = new javax.swing.JComboBox<>();
        cbo_cliente = new javax.swing.JComboBox<>();
        cbo_canal = new javax.swing.JComboBox<>();
        lb_telefono2 = new javax.swing.JLabel();
        cbo_estado = new javax.swing.JComboBox<>();
        lb_telefono3 = new javax.swing.JLabel();
        cbo_metodopago = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbo_productos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableventa = new javax.swing.JTable();
        btnagregarp = new java.awt.Button();
        label1 = new java.awt.Label();
        txt_totalpagar = new javax.swing.JTextField();
        dcfecha_ingresa = new com.toedter.calendar.JDateChooser();
        txt_idproc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_nempresa1.setBackground(new java.awt.Color(204, 255, 255));
        panel_nempresa1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setText("CREAR PEDIDO");

        lb_nombre1.setText("Empleado:");

        lb_ruc1.setText("Cliente:");

        lb_correo1.setText("Canal:");

        lb_telefono1.setText("Fecha pedido:");

        btn_crear1.setText("GUARDAR");
        btn_crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear1ActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        lb_telefono2.setText("Estado:");

        cbo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Enviado", "Nuevo", "Cancelado", "Recibido" }));

        lb_telefono3.setText("Metodo de pago:");

        cbo_metodopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Efectivo", "Tarjeta de credito o debito", "Yape", "Plin", "Transferencia", "Deposito" }));

        jLabel1.setText("Producto:");

        cbo_productos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_productosItemStateChanged(evt);
            }
        });
        cbo_productos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbo_productosPropertyChange(evt);
            }
        });

        jLabel4.setText("Precio:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Stock:");

        tableventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableventa);

        btnagregarp.setLabel("Añadir");
        btnagregarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarpActionPerformed(evt);
            }
        });

        label1.setText("Total a pagar:");

        dcfecha_ingresa.setDateFormatString("yyyy-MM-dd H:mm:ss");

        javax.swing.GroupLayout panel_nempresa1Layout = new javax.swing.GroupLayout(panel_nempresa1);
        panel_nempresa1.setLayout(panel_nempresa1Layout);
        panel_nempresa1Layout.setHorizontalGroup(
            panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_nempresa1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_nempresa1Layout.createSequentialGroup()
                        .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_nempresa1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbo_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txt_idproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_nempresa1Layout.createSequentialGroup()
                                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nombre1)
                                    .addComponent(lb_ruc1)
                                    .addComponent(lb_correo1)
                                    .addComponent(lb_telefono1)
                                    .addComponent(jLabel3)
                                    .addComponent(lb_telefono2)
                                    .addComponent(lb_telefono3))
                                .addGap(18, 18, 18)
                                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbo_empleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbo_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbo_canal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbo_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbo_metodopago, 0, 182, Short.MAX_VALUE)
                                    .addComponent(dcfecha_ingresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panel_nempresa1Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_totalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnagregarp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_nempresa1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_crear1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panel_nempresa1Layout.setVerticalGroup(
            panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nempresa1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombre1)
                    .addComponent(cbo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ruc1)
                    .addComponent(cbo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_correo1)
                    .addComponent(cbo_canal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_telefono1)
                    .addComponent(dcfecha_ingresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_telefono2)
                    .addComponent(cbo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_metodopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_telefono3))
                .addGap(31, 31, 31)
                .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_nempresa1Layout.createSequentialGroup()
                        .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbo_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_idproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_totalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(panel_nempresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_crear1)
                            .addComponent(btn_cancelar))
                        .addGap(34, 34, 34))
                    .addGroup(panel_nempresa1Layout.createSequentialGroup()
                        .addComponent(btnagregarp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_nempresa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_nempresa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear1ActionPerformed
        // TODO add your handling code here:
        registrarVenta();
        Registrardetalle();
    }//GEN-LAST:event_btn_crear1ActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btnagregarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarpActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txt_cantidad.getText())){
            int seleccionado = cbo_productos.getSelectedIndex();
            int idprod = Integer.parseInt(txt_idproc.getText());
            String produ = cbo_productos.getItemAt(seleccionado);
            int cant = Integer.parseInt(txt_cantidad.getText());
            double precio = Double.parseDouble(txt_precio.getText());
            double total = cant * precio;
            int stock = Integer.parseInt(txt_stock.getText());
            if (stock >= cant){
                item = item + 1;
                DefaultTableModel tmp = (DefaultTableModel) tableventa.getModel();
                for (int i = 0; 1 < tableventa.getRowCount(); i++ ){
                    if (tableventa.getValueAt(i, 1).equals(produ)){
                        JOptionPane.showMessageDialog(null, "El producto ya esta seleccionado");
                        return;
                    }
                }
                ArrayList lista = new ArrayList();
                lista.add(idprod);
                lista.add(produ);
                lista.add(cant);
                lista.add(precio);
                lista.add(total);
                Object[] O = new Object[5];
                O[0] = lista.get(0);
                O[1] = lista.get(1);
                O[2] = lista.get(2);
                O[3] = lista.get(3);
                O[4] = lista.get(4);
                tmp.addRow(O);
                tableventa.setModel(tmp);
                txt_cantidad.setText("");
                txt_precio.setText("");
                txt_stock.setText("");
                TotalPagar();
                
            }else{
                JOptionPane.showMessageDialog(null, "stock no disponible");
            }
        }else{
            JOptionPane.showMessageDialog(null, "ingrese cantidad");
        }
            
    }//GEN-LAST:event_btnagregarpActionPerformed

    private void cbo_productosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_productosItemStateChanged
        // TODO add your handling code here:
        
        int seleccionado = cbo_productos.getSelectedIndex();
        
        pro = cp.Buscarpro(cbo_productos.getItemAt(seleccionado));
    
        if (pro.getPrecio_producto() != null){
            txt_idproc.setText(""+pro.getIdtb_producto());
            txt_precio.setText(""+pro.getPrecio_producto());
            txt_precio.setEnabled(false);
            txt_stock.setText(""+pro.getStock_producto());
            txt_stock.setEnabled(false);
            txt_cantidad.requestFocus();
        }
        
    }//GEN-LAST:event_cbo_productosItemStateChanged

    private void cbo_productosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbo_productosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_productosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vpedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vpedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vpedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vpedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vpedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_crear1;
    private java.awt.Button btnagregarp;
    private javax.swing.JComboBox<String> cbo_canal;
    private javax.swing.JComboBox<String> cbo_cliente;
    private javax.swing.JComboBox<String> cbo_empleado;
    private javax.swing.JComboBox<String> cbo_estado;
    private javax.swing.JComboBox<String> cbo_metodopago;
    private javax.swing.JComboBox<String> cbo_productos;
    private com.toedter.calendar.JDateChooser dcfecha_ingresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lb_correo1;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_ruc1;
    private javax.swing.JLabel lb_telefono1;
    private javax.swing.JLabel lb_telefono2;
    private javax.swing.JLabel lb_telefono3;
    private javax.swing.JPanel panel_nempresa1;
    private javax.swing.JTable tableventa;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_idproc;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_totalpagar;
    // End of variables declaration//GEN-END:variables

    private void TotalPagar(){
        totalpagar = 0.00;
        int numFila = tableventa.getRowCount();
        for (int i = 0; i < numFila; i++){
            double cal = Double.parseDouble(String.valueOf(tableventa.getModel().getValueAt(i, 4)));
            totalpagar = totalpagar + cal;
        }
        txt_totalpagar.setText(String.format("%.2f", totalpagar));
    }
    
    private void registrarVenta(){
        
        int seleccionadoE = cbo_empleado.getSelectedIndex();
        String Empleado = cbo_empleado.getItemAt(seleccionadoE);
        
        int idEmpleado = cp.buscarEmpleado(Empleado);
        
        int seleccionadoC = cbo_cliente.getSelectedIndex();
        String Cliente = cbo_cliente.getItemAt(seleccionadoC);
        
        int idCliente = cp.buscarCliente(Cliente);
        
        int seleccionadoCa = cbo_canal.getSelectedIndex();
        String Canal = cbo_canal.getItemAt(seleccionadoCa);
        
        int idCanal = cp.buscarCanal(Canal);
        
        Calendar cal;
        cal = dcfecha_ingresa.getCalendar();
        int d,m,a;
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        
        
        int seleccionadoEs = cbo_estado.getSelectedIndex();
        String Estado = cbo_estado.getItemAt(seleccionadoEs);
        
        int seleccionadoM = cbo_metodopago.getSelectedIndex();
        String Metodo = cbo_metodopago.getItemAt(seleccionadoM);
        
        mp.setIdtb_empleado(idEmpleado);
        mp.setIdtb_cliente(idCliente);
        mp.setIdtb_canales(idCanal);
        mp.setFecha_pedido(new Date(a,m,d));
        mp.setEstado_pedido(Estado);
        mp.setMetodo_pago(Metodo);
        cp.RegistrarPedido(mp);
        
        JOptionPane.showMessageDialog(null, "El pedido se registro correctamente");
        dispose();
    
    }
    
    private void Registrardetalle(){
        int idpedido = cp.IdVenta();
        for (int i = 0; i < tableventa.getRowCount(); i++){
            int idpro = Integer.parseInt(tableventa.getValueAt(i,0).toString());
            int cant = Integer.parseInt(tableventa.getValueAt(i,2).toString());
            double precio = Double.parseDouble(tableventa.getValueAt(i,3).toString());
            
            md.setIdtb_pedido(idpedido);
            md.setIdtb_producto(idpro);
            md.setCant_producto(cant);
            md.setPrecio_unidad(precio);
            cp.RegistrarDetalle(md);
        }
    }

}
